# Do not: include runtime dependencies in this spec
channels:
  - defaults
  - conda-forge
dependencies:
  - coloredlogs
  - conda-merge
  - invoke
  - ipywidgets
  - jupyterlab
  - mamba
  - nodejs
  - mypy
  - pip~=20.2
  - pre-commit
  - shellcheck
  - pydantic
  - pydocstyle
  - pip:
      - black
      - flake8
      - flake8-comprehensions
      - flake8-bandit
      - flake8-bugbear
      - flake8-isort
      - flake8-mutable
      - flake8-docstrings
      - pytest
      - pytest-flake8
      - pytest-bdd
      - pytest-cov
